In [1]:
# Support Vector Regression (SVR)

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('data_files/indicators_final.csv')
dataset.head()

,Name,periodo,lpa,pl,vpa,pVp,pEbit,pEbitda,pAtivos,ebitda,...,roic,evEbit,evEbitda,divPayout,beta,valorizacao,negociosDia,volumeDiario,valorMercado,divYield
0,BBAS3,1998,1.22,5.74,9.31,0.75,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,-12.50,33.15,1.0,4983804.0,0.00
1,BBAS3,1999,1.18,7.09,10.21,0.82,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00,20.69,37.33,0.0,5980565.0,2.62
2,BBAS3,2000,1.37,4.36,11.19,0.53,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.56,-23.53,49.28,0.0,4250473.0,4.19
3,BBAS3,2001,1.52,6.98,12.29,0.86,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.94,72.73,80.02,1.0,7540027.0,2.93
4,BBAS3,2002,2.77,3.54,12.56,0.78,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.12,-3.09,178.60,2.0,7173767.0,6.94

In [3]:
# all rows and columns except the last column
X = dataset.iloc[:, 2:23].values

# all rows, and only the last column
y = dataset.iloc[:, -1].values

In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
# Training the SVR model on the Training set
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [11]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 3.25  5.37]
 [ 4.01  2.33]
 [ 4.41  5.06]
 [ 2.04  0.62]
 [ 4.5   7.3 ]
 [ 3.24  0.  ]
 [ 4.21  2.62]
 [ 1.02  0.  ]
 [ 4.25  1.4 ]
 [ 2.04  0.62]
 [ 5.71 19.86]
 [ 6.13  6.23]
 [ 3.51  1.86]
 [ 3.6   2.91]
 [ 3.14  3.24]
 [ 5.41  6.37]
 [ 2.56  2.5 ]
 [ 4.11  4.7 ]
 [ 6.6  53.38]
 [ 4.98  7.55]
 [ 4.05  2.85]
 [ 5.46 10.58]
 [ 2.9   3.63]
 [ 5.03  4.19]
 [ 3.63  3.46]
 [ 4.77  3.79]
 [ 6.69 47.  ]
 [ 0.84  0.  ]
 [ 5.3   5.89]
 [ 1.65  0.66]
 [ 3.28  0.  ]
 [ 4.03  2.5 ]
 [ 5.71 19.86]
 [ 5.68  6.06]
 [ 2.68  2.76]
 [ 1.97  1.3 ]
 [ 3.38  8.16]
 [ 7.06  8.59]
 [ 3.28  0.  ]
 [ 5.79  8.02]
 [ 4.33  5.21]
 [ 4.05  2.85]
 [ 4.2   3.94]
 [ 2.96  3.28]
 [ 1.63  2.04]
 [ 5.9   9.71]
 [ 0.87  0.8 ]
 [ 5.37  2.58]
 [ 3.27  4.05]]

In [12]:
# Evaluating the Model Performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.1024616264262026